apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: infra-gateway
          name: gateway
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
          ports: 
            - containerPort: 8000